version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: finwallet_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: finwallet_worker
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    restart: always

  mongo:
    image: mongo:7
    container_name: finwallet_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:7
    container_name: finwallet_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data:
