services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: finwallet_api
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      # - mongo
      - redis
    restart: always
    init: true

  vtpass-worker:
    build:
      context: .
      dockerfile: Dockerfile.vtpassWorker
    container_name: finwallet_vtpass_worker
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      # - mongo
      - redis
    restart: always
    init: true

  email-worker:
    build:
      context: .
      dockerfile: Dockerfile.emailWorker
    container_name: finwallet_email_worker
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      # - mongo
      - redis
    restart: always
    init: true

  # mongo:
  #   image: mongo:4.4 # can be changed to 7
  #   container_name: finwallet_mongo
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - mongo_data:/data/db
  #   restart: always

  redis:
    image: redis:7
    container_name: finwallet_redis
    ports:
      - '6385:6379'
    restart: always

# volumes:
#   mongo_data:
# logs_data:
